### ISSUE TITLE
내가 보는 나 질문/답변 페이지 답변 빈칸 하고 이동한 뒤 돌아오면 답변 남아있는 것 수정

### ISSUE THREAD

**Issue by giraff** [giraff/qallah-mini#13]
- [x] 답변이 빈칸이면 넘어가지 못하게 하거나  / 답변을 빈칸으로 수정하고 이동한 뒤 돌아오면 빈칸으로 뜨게 하거나/ 제 3 해결안 제시

**Comment by giraff** [comment]
check list 자유롭게 수정 하기

안바꿔도 될 것 같으면 Close Issue 해도 됨

**Comment by coldexpression** [comment]
제 3해결안 으로 해결
[ 처음 답변 입력 시, 공백이 들어오면 에러 메시지를 출력하고 공백 입력을 받지 않음 ]
