### ISSUE TITLE
내가 보는 나 답변 공백 예외 처리

### ISSUE THREAD

**Issue by giraff** [giraff/qallah-mini#15]
- [x] 답변이 공백일 경우, 다음 버튼을 눌러도 다음 질문으로 넘어가지 않게 하기
- [x] 답변이 공백일 경우, 다음 버튼을 눌렀을 때 에러메시지 인풋 아래에 띄우기
- [x] 공백이 아닌 다른 글자가 입력되는 순간 에러메시지 안 보임

**Comment by coldexpression** [comment]
해결해서 PR 요청 했습니다

**Comment by giraff** [comment]
네 확인
