### ISSUE TITLE
마이페이지 프로필 이미지 업로드 버그

### ISSUE THREAD

**Issue by coldexpression** [giraff/qallah-mini#22]
## 증상
* POST 요청 시, 403 Forbidden error 발생하여 프로필 사진이 변경 되지 않음
## 시나리오
* 마이페이지 -> 프로필 사진 변경 클릭 -> jpeg, png 이미지 선택 -> 확인
## screenshot
![마이페이지 프로필 에러](https://user-images.githubusercontent.com/67794380/124357703-ec521580-dc57-11eb-938e-87b891c2c552.JPG)

## response
```json
```
## 실행 환경
* OS: Windows10 64bit
* Browser: Chrome

**Comment by giraff** [comment]
갑자기 에러가 나타나지 않는다고 하여 내리겠습니다.
