### ISSUE TITLE
Footer CSS 크기에 따른 이슈

### ISSUE THREAD

**Issue by coldexpression** [giraff/qallah-mini#48]
![이슈1](https://user-images.githubusercontent.com/67794380/125317906-54011280-e374-11eb-932c-ab2dee5960bd.JPG)

메인 홈페이지에선 창크기가 변해도 정상적으로 Footer가 잘 작동됨

![이슈2](https://user-images.githubusercontent.com/67794380/125318473-d4277800-e374-11eb-91e9-f1403ed5c0cd.JPG)

마이 페이지에선 height가 1190px 이하이면 정상적으로 Footer가 작동

![이슈3](https://user-images.githubusercontent.com/67794380/125318812-29fc2000-e375-11eb-871d-bfd73982ec99.JPG)

height가 1190px 이상으로 가면 Footer 밑에 빈 공간이 생김

**Comment by giraff** [comment]
굳 수정하고 PR할게요
