### ISSUE TITLE
Console.log() 출력물 정리 작업

### ISSUE THREAD

**Issue by coldexpression** [giraff/qallah-mini#52]
- [ ] Console.log() 출력물 정리 작업

**Comment by coldexpression** [comment]
추가적으로 궁금한게 있음
서버에 올리기 직전에 console.log() 로 찍히는 토큰내용이나 계정정보등은 모두 제거한 채로 올려야함?

**Comment by giraff** [comment]
안해도 돼요. 웹팩 사용해서 안 보이게 할 예정입니다. 

별개로 서버 올리기 전에 중요 정보가 console에 찍힐 수 있기 때문에 모두 제거하는 게 맞습니다.

**Comment by coldexpression** [comment]
그러면 Warning 삭제 보다는 console.log() 삭제하는 방향으로 하겠음

**Comment by giraff** [comment]
console.log() 제거도 안 해도 됨. console에 찍히는 것 모두 다 웹팩으로 해결이 된다는 뜻이었어요ㅠㅠ

console 안나오게 웹팩 설정하면 됨.

**Comment by coldexpression** [comment]
아 ㅇㅋㅇㅋ 그럼 이슈 닫음
