### ISSUE TITLE
프로필 이미지 에러

### ISSUE THREAD

**Issue by giraff** [giraff/qallah-mini#53]
## 증상
* 한 계정에서 로그아웃 하고나서 다른 계정을 로그인하면 이전 계정의 프로필 이미지가 보이고 새로고침을 해야 업데이트 됨.
* 쉽게 말해 다른 회원의 프로필 이미지가 보이는 심각한 버그
## 시나리오
scenario 1 : A 계정 회원가입 후 로그인 -> 이미지 설정 -> 로그아웃 -> B 계정 회원가입 및 로그인 -> 프로필 이미지가 A 계정 것이 잠깐 보임 -> 새로 고침 하고 나서야 B 계정의 프로필 사진이 보임  
B 계정 로그아웃 -> A 계정 로그인 -> B 계정의 프로필 사진이 보임 -> 새로 고침 후 A 계정 프로필 사진이 보임

## screenshot
https://user-images.githubusercontent.com/40794857/125658773-8e3325ce-23b5-41d5-8c68-3dd7a248c5fb.mp4
## response
```json
```
## 실행 환경
* OS: Windows 10
* Browser: Chrome

**Comment by coldexpression** [comment]
확인확인

**Comment by coldexpression** [comment]
PR 요청하였음

**Comment by giraff** [comment]
확인
굳굳
