### ISSUE TITLE
항목별 히스토리 뒤로가기 버튼 이슈

### ISSUE THREAD

**Issue by coldexpression** [giraff/qallah-mini#62]
- 화면 너비 : 560px
![560px](https://user-images.githubusercontent.com/67794380/125951480-909146f0-57c9-48cb-8880-6a58dc09dbe8.JPG)

- 화면 너비 : 768px
![768px](https://user-images.githubusercontent.com/67794380/125951419-ae26ad51-ae20-4c5e-aadd-34f7efb34c02.JPG)

- 화면 너비 :  960px
![960px](https://user-images.githubusercontent.com/67794380/125951447-35ca17f2-20cd-48e9-9ea6-cc5b71e22744.JPG)

화면 너비가 560px 보다 더 작아지면 글씨가 겹치는 문제가 발생함
Back 글씨를 뒤로가기 버튼 바로 뒤에 나타나게 하는 것이 깔끔해 보일꺼 같음

**Comment by giraff** [comment]
PR 했습니다.

**Comment by giraff** [comment]
제가 직접 머지하겠습니다.
