### ISSUE TITLE
서버 올린 후, 나의 답변 DB 조회 버그

### ISSUE THREAD

**Issue by coldexpression** [giraff/qallah-mini#65]
## 증상
* 서버 올리고 나서, 나의 답변 DB 조회가 안됨
* 히스토리에서 이전에 작성한 답변 버튼 클릭 시, 나의 답변 페이지로 이동하지만 데이터가 조회되지 않음
## 시나리오
로그인 -> 마이페이지 -> 나의 답변 -> 나의 답변 데이터들이 출력되지 않음
## screenshot
![히스토리 이슈](https://user-images.githubusercontent.com/67794380/126071588-7572ad4b-dc47-438d-a5a6-fd35ca9ee2bd.JPG)
 
히스토리를 이용해서 답변 일자 파악은 가능함

![히스토리 이슈 2](https://user-images.githubusercontent.com/67794380/126071600-b6bc2842-d3a6-4cc0-903b-23ec73807e8e.JPG)
 
그러나 나의 답변에서 데이터들을 파악할 수 없음
## response
```json
```
## 실행 환경
* OS: Windows10
* Browser: Chrome

**Comment by giraff** [comment]
## 원인1: babel 코드 변환으로 인한 DB query 구문 에러


npm run build 시 
**babel** (ES6+ 최신 문법 -> 호환이 되는 옛날 문법으로 바꿔주는 코드 변환기. 라이브러리 단위로 가져와서 사용) 
을 이용해서 build 폴더를 만들게 되는데

이때 모든 query 구문을 inline 형태로 바꾼다.

원본에서는 db query 작성할때 가독성을 위해서 줄바꿈을 했다

```javascript
// [server>router>api>*]

router.post(` 
   Select 
   FROM *
   WHERE ~
`
```

이것은 현재 줄바꿈 문자가 보이지 않을 뿐.. 줄바꿈이 되었기 때문에 줄바꿈 문자를 포함하고 있다.


```javascript

router.post(`
(/n) 
   Select (/n)
   FROM * (/n)
   WHERE ~(/n)
`
```


babel에 의해서 build 폴더 내에서 db query문들이 inline 으로 바뀌는 변환이 이루어졌고
코드에 줄바꿈한 자리에, 줄바꿈 문자가 그대로 들어가게 되어 에러가 발생했다

```javascript
// [server>build>router>api>*]

router.post(`        \n    SELECT \n FROM * \n WHERE ~           \n`)
```

쿼리문 자체가 줄바꿈 문자로 인하여 제대로 된 구문을 갖추지 못했고 에러가 발생했다.

## 해결

```javascript
router.post(`SELECT  FROM * WHERE ~`)
```

자동으로 줄바꿈을 방지해주는 여러 플러그인을 찾아보았지만
일단 수작업으로 일일이 줄바꿈을 지워주었다.

**Comment by giraff** [comment]
## 원인 2 : 잘못된 api 요청 경로로 인한 경로 에러

(찬식 오빠는 잘 하셨는데, 저의 문제점)

프론트 -> 서버의 router/api 

api로 요청 보낼 때

주소 형식을 잘 갖추어서 써야합니다.

위의 원인 1을 해결하고도 [남이 보는 나]와 [나의 답변] 페이지가 오류가 났는데 (모두 현정 이 작업한 페이지)

원인은 api 요청 보낼때 잘못된 버릇이었습니다.



```
api.post('api/post/ ~')
```
앞에 슬래쉬를 붙이지 않는 나쁜 버릇이 있었습니다.

어떤 설정때문인지 몰라도 이렇게 하면 절대 안 되더라고요.

```
api.post('/api/post/ ~')
```

앞에 슬래쉬 꼭 꼭 붙여주어야 합니다. 

## 해결

위 문제와 관련한 파일을 수정했습니다.

**Comment by giraff** [comment]
build된 파일에서 발생한 문제입니다.

따라서 빌드를 해야하고 

빌드를 위해 코드를 깃에 올린 후 진행해야 한다고 생각해서

main 브랜치에 직접 push 하면서 진행했습니다


따라서 PR은 없습니다.

**Comment by giraff** [comment]
PULL 받으신 뒤, 요청하시면 서버를 키겠습니다.

서버를 키고나서 http://101.101.218.225 로 들어가 해당 이슈와 똑같은 상황에서 테스트 해주세요

번거로우면... pm2 라이브러리 받고 나면 서버를 꺼도 정상 작동 되니까 pm2 설치하면 따로 말씀 드릴게요

**Comment by coldexpression** [comment]
확인해서 이슈 닫아요
