### ISSUE TITLE
히스토리 페이지 이슈

### ISSUE THREAD

**Issue by coldexpression** [giraff/qallah-mini#66]
- 내가보는 나, 남이 보는 나 히스토리 페이지

![이슈 1](https://user-images.githubusercontent.com/67794380/126162181-55f8dd8e-ecb7-4ca3-a8f9-f082d131daaf.JPG)

- 인생의 성찰 히스토리 페이지

![이슈 2](https://user-images.githubusercontent.com/67794380/126162197-597610cb-1044-4f00-abc4-f52f86e12b74.JPG)

내가 보는 나 , 남이 보는 나 히스토리 페이지에서는 '저장한 답변이 없음' 이라고 나옴
하지만, 인생의 성찰 히스토리 페이지에서는 '저장한 답변이 없음' 이라는 문구가 출력 되지 않음

**Comment by coldexpression** [comment]
이슈 해결하여 PR올림

**Comment by giraff** [comment]
확인
